#! /usr/bin/python

__author__="Ramzi Abdoch <raa2148@olumbia.edu>"
__date__ ="$Feb 19, 2015"

import sys
from collections import defaultdict

import fileinput
from count_freqs import Hmm

import math

def usage():
    print """
    python trigram_probs.py [counts_file] [input_file] > [output_file]
        Read in trigram input_file and counts_file generated by 
        training set then calculate log probability of each trigram 
        (line) in input_file.

        Results are stored in the following format:

          <trigram (im2 im1 i)> <log probability>
    """

if __name__ == "__main__":

    if len(sys.argv)!=3: # Expect exactly two arguments: the counts and trigram file
        usage()
        sys.exit(2)

    try:
        counts_file = file(sys.argv[1],"r")
        trigram_file = sys.argv[2]
    except IOError:
        sys.stderr.write("ERROR: Cannot read inputfile %s.\n" % arg)
        sys.exit(1)

    # Initialize a trigram counter
    counter = Hmm(3)
    # Read in counts
    counter.read_counts(count_file)

    # Iterate through trigrams in trigram_file and calculate the log probability of each trigram.
    for line in test_file:
        trigram = line.strip().split(" ")

        if trigram: # Nonempty line
            prob = counter.calc_mle(trigram)

            # Get the log of the probability
            log_prob = math.log(prob)

            # Write log probability to output file
            sys.stdout.write("%s %s %s %s\n" % (trigram[0], trigram[1], trigram[2], str(log_prob)))
        else:
            print ""


